<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: jfons
 * Date: Wed, 18 Jun 2014 12:56:00 +0200
 */

$conf['title'] = 'Materials i recursos per a la formació';
$conf['start'] = 'index';
$conf['lang'] = 'ca';
$conf['template'] = 'wikiformtpl';
$conf['dmode'] = 0775;
$conf['fmode'] = 0664;
$conf['sneaky_index'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register,resendpwd';
$conf['indexdelay'] = 60;
$conf['htmlok'] = 1;
$conf['target']['extern'] = '_blank';
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['plugin']['sidebar']['enable'] = 1;
$conf['plugin']['sidebar']['orientation'] = 'right';
$conf['plugin']['discussion']['allowguests'] = 0;
$conf['plugin']['discussion']['useavatar'] = 0;
$conf['plugin']['discussion']['adminimport'] = 1;
$conf['plugin']['discussion']['subscribe'] = 0;
$conf['plugin']['pagelist']['style'] = 'table';
$conf['plugin']['pagelist']['showheader'] = 1;
$conf['plugin']['pagelist']['showdate'] = '2';
$conf['plugin']['pagelist']['showtags'] = 1;
$conf['plugin']['pagelist']['sort'] = 1;
$conf['plugin']['tagentry']['blacklist'] = '';
$conf['plugin']['tagentry']['height'] = '30';
$conf['plugin']['geogebra']['showHelpUrl'] = 1;
$conf['plugin']['geogebra']['showDownloadUrl'] = 1;
$conf['plugin']['include']['showfooter'] = 0;
$conf['plugin']['include']['showdate'] = 0;
$conf['plugin']['include']['showuser'] = 0;
$conf['plugin']['include']['showcomments'] = 0;
$conf['plugin']['include']['showlinkbacks'] = 0;
$conf['plugin']['include']['showtags'] = 0;
$conf['plugin']['include']['doredirect'] = 0;
$conf['plugin']['include']['doindent'] = 0;

// end auto-generated content
